config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'groups#index'

  resources :users

  resources :groups do
    resources :bills, shallow: true
    member do
      get :show_split
    end
  end

  match ":controller(/:action(/:id))", :via => :get
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :paid_by, class_name: "User", foreign_key: "user_id" 
  belongs_to :group, :touch => true
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users, :through => :memberships

  has_many :bills

  #returns the index of min negative payment in each_person
  def findMaxCreditor
    @balance_graph.index(@balance_graph.min { |a,b| a[:balance] <=> b[:balance] })
  end

  def findMaxDebator
    @balance_graph.index(@balance_graph.max { |a,b| a[:balance] <=> b[:balance] })
  end

  def split_expences

    total_expences = 0
    each_share = 0
    
    each_payment = {}

    users.each do |user|
      each_payment["#{user.id}".to_sym] = 0
    end    

    bills.each do |bill|
      total_expences += bill.amount
      each_payment["#{bill.paid_by.id}".to_sym] = bill.amount
    end

    each_share = total_expences / users.size

    @balance_graph = []

    users.each do |user|
      @balance_graph << {
        user_id: user.id,
        balance: each_share - each_payment["#{user.id}".to_sym]
      }
    end

    weighted_graph = []

    i = 0
    num = @balance_graph.size
    
    while i < num - 1 

      max_creditor = findMaxCreditor
      max_debitor = findMaxDebator
      delete_debitor = false
      delete_creditor = false

      node = {
          node_1: @balance_graph[max_debitor][:user_id],
          node_2: @balance_graph[max_creditor][:user_id],
        }

      transfer = [@balance_graph[max_debitor][:balance], @balance_graph[max_creditor][:balance].abs].min
      node[:weight] = transfer
      
      if @balance_graph[max_debitor][:balance] == transfer
        @balance_graph[max_creditor][:balance] += transfer
        delete_debitor = true
      end

      if @balance_graph[max_creditor][:balance].abs == transfer
        @balance_graph[max_debitor][:balance] -= transfer
        delete_creditor = true
      end

      @balance_graph.delete_at max_debitor if delete_debitor
      @balance_graph.delete_at max_creditor if delete_creditor

      weighted_graph << node
      
      i+=1

    end    

    weighted_graph
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  # Join class of user and group
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :memberships
  has_many :groups, :through => :memberships

  has_many :bills

  #attr_accessible :password, :password_confirmation

  def self.all_except(user)
    where.not(id: user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :dbconnect
  before_action :authenticate_user!
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  def dbconnect
    ActiveRecord::Base.connection
  end

  def after_sign_in_path_for(resource)
    groups_path
  end

  protected
  def configure_devise_permitted_parameters
    registration_params = [:name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  
  before_action :is_member

  def index
    @bills = Group.find(params[:group_id]).bills
  end
  
  def new
    @members = Group.find(params[:group_id]).users
  end

  def create
    new_bill = Bill.create(bill_params)
    new_bill.group = Group.find(params[:group_id])
    new_bill.save
    redirect_to group_bills_path
  end

  def edit
    @bill = Bill.find(params[:id])
    @members = @bill.group.users
  end

  def update
    @bill = Bill.find(params[:id])
    @bill.update!(bill_params)
    redirect_to group_bills_path(@bill.group)
  end

private
  def bill_params
    params.require(:bill).permit(:item, :amount, :user_id)
  end
  
  def is_member
    group = params[:group_id] ? Group.find(params[:group_id]) : Bill.find(params[:id]).group
    unless group.users.exists?(current_user)
      flash[:error] = "You are not a member of the group"
      redirect_to groups_path
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  before_action :is_member, :except => [:index, :new, :create]

  def index
    @groups = current_user.groups
  end

  def new
    @users = User.all_except(current_user)
  end

  def create
    new_grp = Group.create(group_params)
    new_grp.users << current_user
    members = params[:members]
    members.each do |meb|
      new_grp.users << User.find(meb)
    end
    redirect_to groups_path
  end

  def show
    redirect_to group_bills_path(params[:id])
  end
  
  def show_split
    @group = Group.find(params[:id])
    graph = @group.split_expences

    @viewer = current_user
    @other_members = @group.users.all_except(current_user)
    @payements = []
    @other_members.each do |mem|
      link = graph.detect { |node|
        (node[:node_1] == mem.id && node[:node_2] == current_user.id) || (node[:node_1] == current_user.id && node[:node_2] == mem.id)
      }
      if link.nil?
        @payements << "0"
      elsif link[:node_1] == current_user.id
        @payements << "Pay: #{link[:weight]}"
      else
        @payements << "Get: #{link[:weight]}"
      end
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.memberships.destroy_all
    @group.destroy
    redirect_to groups_path
  end

private
  def group_params
    params.require(:group).permit(:name, :summary)
  end

  def is_member
    group = Group.find(params[:id])
    unless group.users.exists?(current_user)
      flash[:error] = "You are not a member of the group"
      redirect_to groups_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bills/_form.html.erb
<div class="bill_form_container">
  <h1>Add Bill</h1>
  <%= form_for(:bill, url: group_bills_path, html: {role: "form"}) do |f| %>

    <div class="field form-group">
      <%= f.label :item %>
      <%= f.text_field :item, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :amount %>
      <%= f.text_field :amount, class: "form-control" %>
    </div>

    <div class="field form-group">
      <label>Paid By</label>
      <%=select(:bill, :user_id, @members.all.collect {|m| [ m.name, m.id ] })%>
    </div>

    <span class="actions">
      <%= f.submit "Add", class: "btn btn-default" %>
    </span>

  <% end %>
</div>

app/views/bills/edit.html.erb
<div class="bill_form_container">
  <h1>Add Bill</h1>
  <%= form_for(@bill, html: {role: "form"}) do |f| %>

    <div class="field form-group">
      <%= f.label :item %>
      <%= f.text_field :item, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :amount %>
      <%= f.text_field :amount, class: "form-control" %>
    </div>

    <div class="field form-group">
      <label>Paid By</label>
      <%=select(:bill, :user_id, @members.all.collect {|m| [ m.name, m.id ] })%>
    </div>

    <span class="actions">
      <%= f.submit "Update", class: "btn btn-default" %>
    </span>

  <% end %>
</div>

app/views/bills/index.html.erb
<% if @bills.size == 0 %>
  <p>No bills in this group, please add bill</p>
<% else %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Date</th>
        <th>Item</th>
        <th>Ammount</th>
        <th>Paid By</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @bills.each do |bill| %>
        <tr>
          <td><%=bill.updated_at %></td>
          <td><%=bill.item %></td>
          <td><%=number_to_currency(bill.amount, :unit => "Rs") %></td>
          <td><%=bill.paid_by.name %></td>
          <td><%=link_to "Edit", edit_bill_path(bill) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= link_to "Add Bill", new_group_bill_path, class: "btn btn-primary btn-lg" %>
<%= link_to "Show Split", show_split_group_path(params[:group_id]), class: "btn btn-success btn-lg" %>

app/views/bills/new.html.erb
<%= render(partial: "form")%>

app/views/groups/index.html.erb
<% if @groups.size == 0 %>
  <h1>Create a New Group</h1>
<% else %>
  <h1>Groups Owned By You</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Summary</th>
        <th>Last Updated</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td><%= group.name%></td>
          <td><%= group.summary%></td>
          <td><%= group.updated_at%></td>
          <td>
            <%= link_to "Add Bill", new_group_bill_path(group), class: "btn btn-default btn-xs btn-primary"%> 
            <%= link_to "View", group_path(group), class: "btn btn-default btn-xs btn-success" %>
            <%= link_to "Delete", group_path(group), class: "btn btn-default btn-xs btn-danger",:method => :delete, :confirm => "Are you sure ?" %>
          </td>
        </tr>  
      <% end %>
    </tbody>
  </table>
<% end %>
<%= link_to "New Group", new_group_path, class: "btn btn-default btn-lg" %>

app/views/groups/new.html.erb
<div class="group_form_container">
  <h1>New Group</h1>

  <%= form_for(:group, url: groups_path, html: {role: "form"}) do |f| %>

    <div class="field form-group">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :summary %>
      <%= f.text_area :summary, class: "form-control" %>
    </div>

    <div class="field form-group">
      <label>Add Members</label>
      <%=select_tag "members", options_from_collection_for_select(@users, "id", "name"),  multiple: true %>
    </div>

    <div class="actions">
      <%= f.submit "Create", class: "btn btn-default" %>
    </div>

  <% end %>
</div>
<script type="text/javascript">
  $("#members").multiSelect();
</script>

app/views/groups/show_split.html.erb
<table class="table table-bordered">
  <h3>For <%=@viewer.name %> in group <%=@group.name %></h3>
  <thead>
    <tr>
      <th>Member</th>
      <% @other_members.each do |mem| %>
        <th><%=mem.name %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%=@viewer.name%></td>
      <% @payements.each do |p| %>
        <td><%=p %></td>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mysplit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">MySplit</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.nil? %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% else %>
          <li><%= link_to 'Edit account', edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="flash #{key} alert alert-warning">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%=value %>
    </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>